name: Build and Deploy

on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm ci, lint, test, and build
        run: |
          npm --prefix "$PWD/functions" ci
          npm --prefix "$PWD/hosting" ci
          npm --prefix "$PWD/functions" run lint
          npm --prefix "$PWD/functions" run build
          npm --prefix "$PWD/hosting" run build
        env:
          CI: true
      - name: Deploy to Firebase (only master branch)
        if: github.ref == 'refs/heads/master'
        run: |
          npm install -g firebase-tools
          firebase deploy --token "$FIREBASE_TOKEN"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
